services:
  # --- Frontend (Next.js) ---
  - type: web
    name: conu-planner-frontend
    env: node
    plan: free
    rootDir: .             # <-- frontend is at repo root
    buildCommand: npm ci && npm run build
    startCommand: npm run start -- -p 3000
    autoDeploy: true
    envVars:
      - key: COMMUNITY_API_URL
        value: https://conu-community.onrender.com
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 20

  # --- Community backend (Express + Puppeteer + Snoowrap) ---
  - type: web
    name: conu-community
    env: node
    plan: free
    rootDir: conu-community
    buildCommand: npm ci && npx puppeteer browsers install chrome
    startCommand: npm run start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 20
      - key: REDDIT_USER_AGENT
        sync: false
      - key: REDDIT_CLIENT_ID
        sync: false
      - key: REDDIT_CLIENT_SECRET
        sync: false
      - key: REDDIT_USERNAME
        sync: false
      - key: REDDIT_PASSWORD
        sync: false
      - key: CHROME_FLAGS
        value: --no-sandbox --disable-setuid-sandbox --disable-dev-shm-usage --disable-gpu --headless=new
